// Code generated by tools/gen from schema/tools.json. DO NOT EDIT.

package cli

// genToolCommands 是官方 MCP 工具到 CLI 子命令的静态映射表，
// 由 toolcmd.go 在 init 时注册为 cobra 命令。
var genToolCommands = []toolCommand{
	{
		use:   "query-shop-list",
		tool:  "queryShopList",
		short: "瑞幸咖啡查询门店列表",
		params: []toolParam{
			{flag: "longitude", key: "longitude", kind: kindNumber, required: true, desc: "经度"},
			{flag: "latitude", key: "latitude", kind: kindNumber, required: true, desc: "纬度"},
			{flag: "dept-name", key: "deptName", kind: kindString, required: false, desc: "门店名称"},
		},
	},
	{
		use:   "search-product",
		tool:  "searchProductForMcp",
		short: "瑞幸咖啡根据用户传入query， 匹配商品推荐结果",
		params: []toolParam{
			{flag: "dept-id", key: "deptId", kind: kindInteger, required: true, desc: "门店ID"},
			{flag: "query", key: "query", kind: kindString, required: true, desc: "用户原始查询文本"},
		},
	},
	{
		use:   "switch-product",
		tool:  "switchProduct",
		short: "瑞幸咖啡商品属性切换",
		params: []toolParam{
			{flag: "dept-id", key: "deptId", kind: kindInteger, required: true, desc: "门店ID"},
			{flag: "product-id", key: "productId", kind: kindInteger, required: true, desc: "商品ID"},
			{flag: "sku-code", key: "skuCode", kind: kindString, required: true, desc: "商品SKU编码"},
			{flag: "attr-operation-param", key: "attrOperationParam", kind: kindJSON, required: true, desc: "商品属性切换参数"},
			{flag: "amount", key: "amount", kind: kindInteger, required: true, desc: "商品数量"},
		},
	},
	{
		use:   "query-product-detail-info",
		tool:  "queryProductDetailInfo",
		short: "瑞幸咖啡查询商品详情",
		params: []toolParam{
			{flag: "dept-id", key: "deptId", kind: kindInteger, required: true, desc: "门店ID"},
			{flag: "product-id", key: "productId", kind: kindInteger, required: true, desc: "商品ID"},
		},
	},
	{
		use:   "preview-order",
		tool:  "previewOrder",
		short: "瑞幸咖啡订单预览",
		params: []toolParam{
			{flag: "dept-id", key: "deptId", kind: kindInteger, required: true, desc: "门店ID"},
			{flag: "product-list", key: "productList", kind: kindJSON, required: true, desc: "订单商品列表"},
		},
	},
	{
		use:   "create-order",
		tool:  "createOrder",
		short: "瑞幸咖啡创建订单",
		params: []toolParam{
			{flag: "dept-id", key: "deptId", kind: kindInteger, required: true, desc: "门店id"},
			{flag: "product-list", key: "productList", kind: kindJSON, required: true, desc: "订单商品列表"},
			{flag: "longitude", key: "longitude", kind: kindNumber, required: true, desc: "经度"},
			{flag: "latitude", key: "latitude", kind: kindNumber, required: true, desc: "纬度"},
			{flag: "coupon-code-list", key: "couponCodeList", kind: kindStringSlice, required: false, desc: "优惠券列表，此参数来自 `previewOrder` 的返回字段 `couponCodeList`"},
		},
	},
	{
		use:   "query-order-detail-info",
		tool:  "queryOrderDetailInfo",
		short: "瑞幸咖啡查询订单详情",
		params: []toolParam{
			{flag: "order-id", key: "orderId", kind: kindString, required: true, desc: "订单ID"},
		},
	},
	{
		use:   "cancel-order",
		tool:  "cancelOrder",
		short: "瑞幸咖啡取消订单",
		params: []toolParam{
			{flag: "order-id", key: "orderId", kind: kindString, required: true, desc: "订单ID"},
		},
	},
}
